### ISSUE TITLE
extra line in Android

### ISSUE THREAD

**Issue by skyride99** [evblurbs/react-native-md-textinput#1]
This is a great control. Just a little bug in Android 
<img width="472" alt="screen shot 2016-02-10 at 3 26 27 pm" src="https://cloud.githubusercontent.com/assets/3801142/12941244/66cf549e-d00b-11e5-898c-cc6035f6d437.png">

**Comment by skyride99** [comment]
An extra faint line underneath. In iOS looks great. Is there a way to set that line to white?

**Comment by skyride99** [comment]
set
					underlineColorAndroid={'white'}

fixes the issue

**Comment by evblurbs** [comment]
I've updated the TextInput to have a default prop that sets the underline color to transparent. You shouldn't have to add that prop now. Thanks for catching this! I need to do more Android testing.

**Comment by RickFrom1987** [comment]
Thanks for the quick fix!
