### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by jojonarte** [evblurbs/react-native-md-textinput#13]
I'm having the kind of issue with the code below and please also see screenshot

`/**
 * 
 * https://github.com/facebook/react-native
 */
import TextField from 'react-native-md-textinput';

import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  Image,
  Dimensions,
  PixelRatio,
  TextInput
} from 'react-native';

export default class RegistrationForm extends Component {
  render(){

    return(
      <TextField
         label={'Name'}
         highlightColor={'#00BCD4'}
         keyboardType={'numeric'}
       />
    )

  }
}
`

Can you tell me how this could get fixed? I'm using ReactNative 

My package.json is below too
`{
  "name": "test_mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.1",
    "react-native-md-textinput": "^1.9.2"
  }
}
`

![screen shot 2016-05-23 at 4 29 46 pm](https://cloud.githubusercontent.com/assets/11880365/15464671/37694c98-2103-11e6-9dce-0b7ebace1706.png)

**Comment by ruaan** [comment]
here too

**Comment by evblurbs** [comment]
Pull Request #8 resolves this issue. Just change the version in your package.json to:

`"react-native-md-textinput": "^2.0.0"`

Thanks!
