### ISSUE TITLE
[Feature] Set the input field content on render

### ISSUE THREAD

**Issue by aviadhahami** [evblurbs/react-native-md-textinput#22]
Hi, 
I would like to suggest a feature.
This will expose a prop `initialContent = "myString"` which will yield the component with the text already inserted (some like binding an input field to scope variable in angular)

**Comment by aviadhahami** [comment]
Ok, as I suspected this prop exists in [TextField.js#L13](https://github.com/evblurbs/react-native-md-textinput/blob/master/lib/TextField.js#L13) yet not exposed in the official docs.
Any particular reason for there?

**Comment by antoinerousseau** [comment]
the `value` props is standard in React

http://facebook.github.io/react-native/releases/0.32/docs/textinput.html#value

**Comment by aviadhahami** [comment]
@antoinerousseau yes, but this is a higher-order component thus it is not obvious

**Comment by antoinerousseau** [comment]
ok you can close this issue then ;)

**Comment by evblurbs** [comment]
I'm the docs I mention all props are passed to the TextField component, and link to the TextField props documentation. I have an example of using the TextField props to display a numeric keyboard. Maybe adding an example with the value prop will help? I'm not going to document all the TextField props though.

**Comment by aviadhahami** [comment]
@evblurbs yes, I think this can help as this is a common usecase
@antoinerousseau but ummm 
![but ummm](https://media.giphy.com/media/UvwI1X7XkbXq0/giphy.gif)
