### ISSUE TITLE
Cannot change the color of input text

### ISSUE THREAD

**Issue by bubuzzz** [evblurbs/react-native-md-textinput#5]
Is there a way to change the color of the input text ? I am on the way to investigate React Native for my start up and come across your project, which is exactly what i need right now. I know that you already put in the ToDo list about supporting the dark theme, but can it be expanding to styling the color for the input text ?

**Comment by philipshurpik** [comment]
Hi!
You can look at this pull request and possibly fork our branch (before it will be merged in master) 
#4

**Comment by bubuzzz** [comment]
@philipshurpik thank buddy

**Comment by evblurbs** [comment]
@bubuzzz I started working on @philipshurpik pull request and pulled in the options to style the TextInput, FloatingLabel, and View wrapper.

I've also added the props `textColor`, `textFocusColor`, and `textBlurColor` to give more control of the TextInput's color. Let me know if that addresses your issue!
